apiVersion: v1
kind: Service
metadata:
  name: circle-test-app
  labels:
    app: circle-test-app
spec:
  # uncomment the following line if you want to use a LoadBalancer
  # type: LoadBalancer
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
  selector:
    app: circle-test-app